### ISSUE TITLE
POST Error from  /stott.security.optimizely/api/cspreporting/reporttoviolation/ in Azure Application Insights

### ISSUE THREAD

**Issue by Sabah-Tahir** [GeekInTheNorth/Stott.Security.Optimizely#202]
We have noticed several POST errors originating from "/stott.security.optimizely/api/cspreporting/reporttoviolation/" in Application Insights. These errors have been occurring since our website went live on March 28th, with a response code of 405.

![image](https://github.com/GeekInTheNorth/Stott.Security.Optimizely/assets/26634891/8462cfac-107e-46e0-8ee9-5ccf5de4fcd4)

**Comment by GeekInTheNorth** [comment]
Hello @Sabah-Tahir ,

I have had another person reach out with a similar issue. The exception information revealed that this was caused by the information being too large for the database index.

Can you confirm if your exception information says the same cause?

Ideally to reproduce and resolve this issue I will need the payload sent to the report-to endpoint. Can you provide this or share a URL where this is being raised so I can try and capture this?

Please note that error handling exists and this merely means you won't have the data for this violation saved. This will not prevent the Add-on from protecting your website.

Regards
Mark

**Comment by Sabah-Tahir** [comment]
Thank you, @GeekInTheNorth, for your prompt response. Are you considering adding the functionality to truncate the reported URI if it exceeds the threshold? I'm not sure what the next steps are for us in this situation.

**Comment by GeekInTheNorth** [comment]
Hello @Sabah-Tahir 

Yes I will be implementing a fix to truncate a reported URI if it exceeds the threshold.

You do not need to worry or take any actions.  The fact a browser has sent this report means the browser has already blocked the URL in question. 

When a fix is released, I'll tag you here on this issue to let you know that the updated version is ready to install.

Regards,
Mark

**Comment by Sabah-Tahir** [comment]
Great, Thanks @GeekInTheNorth

**Comment by GeekInTheNorth** [comment]
I've updated the CSP Violation Reporting as such:

When cleaning the report data to save the report:
- Check the reported URL
  - Clean the URL to just the Host and Path
  - If the Host and Path exceeds 255 characters, then clean the URL to just the Host
  - If the Host alone is still greater than 255 characters, then don't save the violation report
- Check the violated directive
  - If the violated directive is not in the list approved by the module, then don't save the violation report

**Comment by GeekInTheNorth** [comment]
Hello @Sabah-Tahir

This is now live in version 2.6.0, you can read more here: https://github.com/GeekInTheNorth/Stott.Security.Optimizely/discussions/207

**Comment by Sabah-Tahir** [comment]
Thanks @GeekInTheNorth. I will try this version and will let you know how it goes.
